### ISSUE TITLE
Compare to dev theme

### ISSUE THREAD

**Issue by Bad3r** [UNICKCHENG/developer-theme-for-logseq#1]
Hiey there!
What are the differences between this version and dev theme?
Also please adf screenshots to the readme to make it easier for users to discover your theme

**Comment by UNICKCHENG** [comment]
Thank you for the tip, I added some descriptions and pictures just now.
At the moment it is easy to compare the two, they both have their own websites

**Comment by UNICKCHENG** [comment]
> Hiey there! What are the differences between this version and dev theme? Also please adf screenshots to the readme to make it easier for users to discover your theme

@Bad3r  Thank you for the tip, I added some descriptions and pictures just now.
At the moment it is easy to compare the two, they both have their own websites
