### ISSUE TITLE
建議加上 inline code block 的顏色

### ISSUE THREAD

**Issue by ghost** [UNICKCHENG/developer-theme-for-logseq#10]
Inline code block `像這樣` 目前文字並沒有任何高亮，因此很難一眼看出它是 code block，希望可以針對它加上文字及/或背景的高亮。

**Comment by UNICKCHENG** [comment]
Hi, @nelson-dai-17Live 非常抱歉，因為我的疏忽，導致了 inline code block 背景色沒有生效，我已經更新了代碼，請嘗試更新到最新版本。

**在設計之初，我擔心 inline code block 的顏色有礙於正文的閱讀，因此選擇了與背景色相近的顏色。**

1）如果您希望對文字有高亮或者突出的效果，建議嘗試以下替代方案

![image](https://user-images.githubusercontent.com/32270702/222727602-f347537a-a01a-4b11-9cde-5b26bf3d888f.png)

2）如果您希望自定義  inline code block  背景色，可以在 `custom.css` 中添加下述配置

```
/* 需要將 red 替換為您自定義的顏色 */
:not(pre) > code {
    background-color: red;
}
```

如果您有更好的 color 方案，歡迎一起來交流

**Comment by ghost** [comment]
好的，謝謝你
