### ISSUE TITLE
window control buttons are covered by left sidebar

### ISSUE THREAD

**Issue by lee88688** [UNICKCHENG/developer-theme-for-logseq#36]
![image](https://github.com/UNICKCHENG/logseq-developer-theme/assets/5847884/de02f029-2b6e-4316-a9dc-5b8828644a0c)

**Comment by UNICKCHENG** [comment]
This seems to occur in the latest version of Logseq. You can try using the default Logseq theme to see if it reproduces this issue.

![logseq](https://github.com/UNICKCHENG/logseq-developer-theme/assets/32270702/fd51d631-f768-4024-b478-9fa3ea8d7a14)

**Comment by lee88688** [comment]
when update to latest version, this problem is fixed. but the line below window buttons is absent.
![image](https://github.com/UNICKCHENG/logseq-developer-theme/assets/5847884/0565ccc9-b6a9-489f-a999-41a299d60619)

**Comment by UNICKCHENG** [comment]
Hi, in the latest version, I have removed these lines ~

![image](https://github.com/UNICKCHENG/logseq-developer-theme/assets/32270702/951e61ea-f724-4b97-9230-7f338108b5b6)
