### ISSUE TITLE
一些标签不会居右

### ISSUE THREAD

**Issue by butfool** [UNICKCHENG/developer-theme-for-logseq#4]
![image](https://user-images.githubusercontent.com/61893561/212807598-582b4b56-d554-48bb-9837-ed9bd99ffed6.png)

如图所示，一些标签无法居右

LogSeq：0.8.16
DeveloperTheme: 1.1.3
Windows10

**Comment by butfool** [comment]
和顺序无关，似乎和数量有关，只能有三个居右的

**Comment by UNICKCHENG** [comment]
> ![image](https://user-images.githubusercontent.com/61893561/212807598-582b4b56-d554-48bb-9837-ed9bd99ffed6.png)
> 
> 如图所示，一些标签无法居右
> 
> LogSeq：0.8.16 DeveloperTheme: 1.1.3 Windows10

很遗憾，目前不支持  `#QUES` 标签居右显示，不过您可以考虑将下述代码复制到 `custom.css` 中，来实现这一操作
```
@media (min-width: 640px) {
    a.tag[data-ref=QUES],
    a.tag[data-ref=ques],
    a.tag[data-ref=question] {
      position: relative;
      float: right;
      top: 11%;
    }
}
```

目前只支持以下标签居右显示

- `#Bug`、`#bug`
- `#feat`、`#Improvement` 、`#improvement`
- `#perf` 、`#feature`、`#Feature`
- `#docs` 、`#Documentation`、`#documentation`
- `#idea`、`#Idea`

考虑到一段内容中增加太多标签，可能会破坏段落的阅读性，所以只设置了部分标签可以居右显示

如果您有更好的改进建议，欢迎指出

ASPA: `#QUES` 标签将会在下一个版本得到支持

**Comment by butfool** [comment]
明白了，原来是我没有设置
