### ISSUE TITLE
Swift code block 顏色難以閱讀

### ISSUE THREAD

**Issue by ghost** [UNICKCHENG/developer-theme-for-logseq#7]
<img width="1179" alt="image" src="https://user-images.githubusercontent.com/90598131/217182814-361d742a-bad9-476b-b94f-ea1b5d8174e9.png">

如圖，Swift 的函式名稱跟背景顏色太接近，難以閱讀。我用的是 v1.2.2 版

**Comment by UNICKCHENG** [comment]
@nelson-dai-17Live   謝謝指正，已經修復，請更新到最新版本

最新樣式如下：

![image](https://user-images.githubusercontent.com/32270702/217211889-80b147bf-0c3f-482b-88e7-09de3ba66e2e.png)
